version: "3.9"
services:
  filesystem-microservice:
    container_name: filesystem-microservice
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8080"
    networks:
      - filesystem_microservice_network
      - inter_server_connection

networks:
  filesystem_microservice_network:
    name: filesystem_microservice_network
    driver: bridge
  inter_server_connection:
    external: true