version: '3.9'
services:
  filesystem-microservice:
    container_name: filesystem-microservice
    image: smighty/filesystem-service:latest
    ports:
      - "8081:8080"
    networks:
      - filesystem_microservice_network
      - microservices

networks:
  filesystem_microservice_network:
    name: filesystem_microservice_network
    driver: bridge
  microservices:
    external: true