apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesystem-microservice
spec:
  selector:
    matchLabels:
      app: filesystem-microservice
  template:
    metadata:
      name: filesystem-microservice
      labels:
        app: filesystem-microservice
    spec:
      containers:
        - name: filesystem-microservice
          image: team-f-filesystem-microservice-jvm
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: filesystem-microservice
spec:
  selector:
    app: filesystem-microservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080